### ISSUE TITLE
did parse-stack covered all parse server API's? 

### ISSUE THREAD

**Issue by rmros** [modernistik/parse-stack#10]
@apersaud did parse-stack covered all parse server API's? like Objects , Users , Sessions , Roles , Files , Analytic ,  Push Notifications , Installations , Cloud Functions , Schema s , Apps , Function Hooks , Trigger Hooks with HTTP Verbs?

**Comment by apersaud** [comment]
We cover most of the Parse Server APIs including the special tables, specifically [documented here](https://github.com/modernistik/parse-stack) - and we will be adding more as [Parse-Server](https://github.com/ParsePlatform/parse-server) continues to evolve. Not everything is supported though, but we accept good contributions.
