### ISSUE TITLE
Support combining scopes with .all or .save_all

### ISSUE THREAD

**Issue by mstorch** [modernistik/parse-stack#19]
Assuming we have a model called Booking, with a "has_many" property :applications, and we wish to change a booking's :submitted applications to :rejected, it is currently not possible to do the following:

```ruby
booking.applications(status: :submitted).save_all do |application|
  application.status = :rejected
end
```

This will actually discard the sub-query (status: :submitted) and the block will operate on the first 100 Application records it finds, even they are unrelated to the Booking.

A suitable workaround is the following, but would be nice if the above was supported.

```ruby
applications = booking.applications(status: :submitted).to_a
applications.each do |application|
    application.status = :rejected
end
applications.save
```

**Comment by apersaud** [comment]
Will be available in 1.6.0
