### ISSUE TITLE
How to Authenticate a User using the Parse::User class

### ISSUE THREAD

**Issue by maxdignan** [modernistik/parse-stack#2]
I can't figure it out, because I run Parse::User.where username, password and get permission denied. And of course I have access to other parts of the Parse Server.

**Comment by apersaud** [comment]
Hi @maxdignan, login functionality hasn't been implemented yet. I will test it out, but I don't believe you can query your Parse app through he password field (it might be one of the few that are protected).

The API you are looking for is here: [https://parse.com/docs/rest/guide#users-logging-in](https://parse.com/docs/rest/guide#users-logging-in)

You could use `Parse::Client` instance to make the manual REST API call for now until it is implemented in the `Parse::User` model. See [Querying Directly](https://github.com/modernistik/parse-stack#parse-rest-api-client)

**Comment by apersaud** [comment]
Working on login: https://github.com/modernistik/parse-stack/pull/5

**Comment by apersaud** [comment]
login, logout and session functionality: 3028a2b8f370b028fd2c4fdb541513f7629829b8

Will be available in 1.4.4
