### ISSUE TITLE
Needs RubyDoc/YARD documentation.

### ISSUE THREAD

**Issue by apersaud** [modernistik/parse-stack#3]
Need to document all public level APIs with ruby documentation engine, since not everything has been covered in the README.md.

**Comment by rmros** [comment]
preparing wiki is not bad choice for documents

**Comment by apersaud** [comment]
A lot of documentation has been added in v1.5.2. Will continue to update going foward. http://www.rubydoc.info/github/modernistik/parse-stack/Parse/Object
