### ISSUE TITLE
Setting class object with "Master Key Only" ACLs returns an object with Public Read/Write ACLs

### ISSUE THREAD

**Issue by hrodriguezfigueroa** [modernistik/parse-stack#32]
Steps to reproduce: 
1. Go to the Browser screen in your Parse Dashboard and select a class with data.
2. Pick any object in the class and change its ACLs to Master Key Only (i.e. remove all access Public or otherwise)
3. Either set a breakpoint in your class after save hook to inspect the object or just refetch the object you just modified. 
4. In either case inspect the object ACLs. You should see Public Read/Write access.

**Comment by apersaud** [comment]
Thanks, adding a note here:

We'll need to reconfigure `Parse::ACL` to support setting different default ACLs per class for new objects, but getting an empty ACL hash from Parse, should imply 'Master Key Only' for that record and not apply the class defaults.
