### ISSUE TITLE
method "update" in model

### ISSUE THREAD

**Issue by edudouglas** [modernistik/parse-stack#33]

**Comment by apersaud** [comment]
_Added the issue back to the issue in case anyone else had the same question_

You might want to revisit the information about updating records here: https://github.com/modernistik/parse-stack#creating-saving-and-deleting-records

You can update objects using regular defined property accessors or using the [`attributes`](https://www.modernistik.com/gems/parse-stack/Parse/Properties.html#attributes=-instance_method) method if desired. While there is an `update` method for Parse::Object subclasses, however, it is recommended to [`save`](https://www.modernistik.com/gems/parse-stack/Parse/Core/Actions.html#save-instance_method) instead. I would also not recommend blindly setting incoming parameter values into the hash for security reasons. It is recommended to using [Strong Parameters as described](http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters)

Given your example, you could rewrite it to:

```ruby
def update
    @film = Film.find params[:id]
    # use Strong Parameters instead of mass hash assignment.
    @film.attributes = params.permit() # set the keys you want
    if @film.save
      redirect_to @film
    else
      render 'edit'
    end
end
```
