### ISSUE TITLE
Failed to display relationships after restarting server

### ISSUE THREAD

**Issue by Lozadaa** [modernistik/parse-stack#36]
When creating relationships, everything works perfect, creating the rows with relationships as well. The problem is in the view, after the relationships already exist and you want to see it after restarting the server are not seen.

The quick fixes I found to this were:

Go into the view of each table and then go to the view of those containing the relationships and already looked perfectly.

Create a row in the table with the relationships and delete it.

Is there any official solution to this? Has anyone else noticed it?

**Comment by apersaud** [comment]
Do you mean seeing the changes in the Parse Dashboard?
