### ISSUE TITLE
Cloud code functions never returning

### ISSUE THREAD

**Issue by nilsk123** [modernistik/parse-stack#40]
Calling cloud code from the rails parse stack always times out, call is as such:

`Parse.call_function :getNumberOfChallengesPerDay, {}`

Server logs show it coming in but rails console always times out

**Comment by apersaud** [comment]
Can you provide a small example where it is reproducible? (Since we are running the latest in production and don't see this happening).

You might consider if there is something in the implementation of the call where the web worker times out in order to response (especially if you are debugging).

**Comment by apersaud** [comment]
I have verified all that installations using parse-stack have no issues with calling cloud functions. Closing this issue as it is currently stale and haven't received updates.
