### ISSUE TITLE
Any example of having two ParseServer connections at same time? 

### ISSUE THREAD

**Issue by taijizhu** [modernistik/parse-stack#47]
I need to sync data across two parseserver db.  Right now, I could not figure out how to open two connections and switch them dynamically.

**Comment by apersaud** [comment]
Sorry for the delay, this is supported. You can have any number of clients configured, by default all objects use the client with the `:default` symbol.

Basically every class can point to a different Parse::Client (each pointing to a different server) by overriding their client instance they are using. If you set the proper client on each of the classes, you can then save objects related to those collections independently.

https://www.modernistik.com/gems/parse-stack/Parse/Client/Connectable.html#client-instance_method
