### ISSUE TITLE
Version on rubygems.org has old dependencies.

### ISSUE THREAD

**Issue by Beartech** [modernistik/parse-stack#52]
Person here: https://stackoverflow.com/questions/60676648/featured-error-bundler-could-not-find-compatible-versions-for-gem-activesuppo/60677522#60677522
is having a problem with installing the gem from rubygems.org because their rails is > 6 but the version 1.8 on rubygems says 'activesupport < 6, >= 4.2.1'.

I advised them to pull from here for their gemfile, but since you are advising it works with "< 7" here, do you need to do a new push to rubygems.org?

**Comment by apersaud** [comment]
Thanks, I will update and make a new release. We only support ActiveModel < 6 at the moment since I notice some tests fail. Will look into supporting ActiveModel 6+.

**Comment by apersaud** [comment]
Updated https://rubygems.org/gems/parse-stack to 1.8.1.

Will add support for the latest ActiveModel library soon.
