### ISSUE TITLE
why didn't inherited

### ISSUE THREAD

**Issue by rmros** [modernistik/parse-stack#7]
why didn't inherited Parse::Object from Active Record and Active model ?
can u integrated parse stack with ruby on rails?
for example: rails g migrate post name:string 
will integrated via pars server

**Comment by apersaud** [comment]
Hi @rmros,

We inherited from Active model, but not Active Record. Active Record uses a database backing store (usually PostgresQL) and its interfaces are directly tied to the database backing store (SQL query language). ParseStack communicates directly with the Parse-Server REST API to make all the queries and ORM operations - which depend on your keys for authentication and your webhook before/after saves and deletes that are setup.

In terms of Rails, I agree it might be a good idea to write some additional rails functionality to help users utilize ParseStack inside of a rails app. However, for now, you can easily write all your models directly in code and just call `Parse.setup` as an initializer with your keys.

**Comment by rmros** [comment]
can u contribute your project?

**Comment by rmros** [comment]
Hi @apersaud 
Thank you for your thorough answer ♥

i think this code need change ☺

```
 RailsApp::Application.routes.draw do
    mount Parse::Webhooks, :at => '/webhooks'
  end

```
**to**
```

 Rails::Application.routes.draw do
    mount Parse::Webhooks, :at => '/webhooks'
  end
```




-----------------------------


i put this code in config.ru
```
map "/webhooks" do
    run Parse::Webhooks
  end
```

and then put this code to \config\route.rb
```
Rails::Application.routes.draw do
    mount Parse::Webhooks, :at => '/webhooks'
  end
```

but dont know how use Webhook to mount another rails application

**Comment by apersaud** [comment]
@rmros,

I have added some hooks into Rails to make installation and model generation easier - with updated instructions. It is currently only available in the [`master` branch](https://github.com/modernistik/parse-stack/tree/master).

Thanks for the documentation change, I have fixed the typo. On your second question between using `config.ru` and `Rails.application.routes.draw` - it is up to you whether you want to mount the application in the `config.ru` (using the Rack interface) or have Rails mount it for you through in the `routes.rb` file. Though, you should only pick one.
