### ISSUE TITLE
 rake parse:upgrade                        # Run auto_upgrade on all of your Parse models

### ISSUE THREAD

**Issue by rmros** [modernistik/parse-stack#9]
@apersaud  i cant understand --> **rake parse:upgrade**
for example : 
suppose we have a Song class and inherited Parse::Object
```
class Song <  Parse::Object
  property :name
  property :play, :integer
  property :audio_file, :file
  property :tags, :array
  property :released, :date
  belongs_to :artist
  # `like` is a Parse Relation to User class
  has_many :likes, as: :user, through: :relation
end 
```
and then we operate to make tables
`Song.auto_upgrade!`

and we had some records in that : 

```
artist = Artist.first(:name.like => /Sinatra/, :genres.in => ['swing'])
song = Song.new name: "Fly Me to the Moon"
song.artist = artist
song.audio_file = Parse::File.create("http://path_to.mp3")
song.likes.add Parse::User.first(username: "persaud")
song.save
```

 **so what will do  rake parse:upgrade  ?√**

**Comment by apersaud** [comment]
`auto_upgrade!` uses the Parse-Server Schema REST API to upgrade your Parse classes (tables/colllections) while being non-destructive. This tries to make the schema match the model. It will create new tables/classes and add columns to existing classes. It will not delete any columns or collections.

Using `rake parse:upgrade` is a helper Rake task to upgrade all of your schemas (collections) with Parse-Server based on your defined models (internally it calls `Parse.auto_upgrade!`). 

Calling `Song.auto_upgrade!`, would do the same thing except it only upgrades the schema `Song` for your Parse app. 

You can choose how you would like to upgrade your Parse-Server tables, if at all. Either upgrading all of them with the rake task, or inside your code by calling `auto_upgrade!` on any of your models. This is modeled after how [`DataMapper`](http://datamapper.org/getting-started.html) handled auto_upgrade.

I will update the documentation to make it more clear, and possibly write an example app.
